[package]
name = "steganography"
version = "0.2.1"
authors = ["Teo Voinea <voinea.teodor@gmail.com>"]
description = "A simple steganography library"
respository = "https://github.com/teovoinea/steganography"
readme = "README.md"
keywords = ["image", "steganography"]
categories = ["encoding"]
license = "MIT"

[dependencies]
image = "0.12.3"
